language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install postgresql 
  - sudo apt-get -y install gcc
  - sudo apt-get -y install python3-dev
  - sudo apt-get -y install musl-dev
  - './.travis/main.sh'
install:
  - pip install pytest-pylint==0.16.1
  - pip3 install flask
  - pip3 install psycopg2==2.7.6 
  - pip3 install httpcore==0.12.0
  - pip3 install httpx==0.16.1
  - pip3 install redis==3.5.3

script:
  - pytest --pylint --pylint-error-types=EF 

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make build && make publish;
      echo "Deploy to --> PRO environment"
    fi
  - if [[ "$TRAVIS_BRANCH" == "staging" ]]; then
      echo "Deploy to --> staging environment"
    fi
  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then
      echo "Deploy to --> dev"
    fi
