version: '3'
services:
  dbmeasures:
    image: dbmeasures
    container_name: dbmeasures
    build: postgres/. 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  api2json:
    image: api2json 
    container_name: api2json
    build: api/.
    depends_on:
      - dbmeasures 
    links:
     - dbmeasures
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}



