version: '3'
services:
  dbmeasures:
    image: dbmeasures
    container_name: dbmeasures
    build: postgres/. 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  api2json:
    image: api2json 
    container_name: api2json
    build: api/.
    depends_on:
      - dbmeasures 
    links:
     - dbmeasures
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=${REDIS_HOST}
      - REDIS_REPLICATION_MODE=master  
    container_name: redis
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    ports: 
      - 6379:6379
    command: 
      - --save 900 1
      - --requirepass ${REDIS_PASSWORD} 
  rediscache:
    image: rediscache
    container_name: rediscache
    build: cache/.
    ports:
      - 5005:5005
    depends_on:
    - redis 
    links:
     - redis
     - api2json
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
