apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api2json
  name: api2json
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api2json
status:
  loadBalancer: {}
