apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rediscache 
  name: rediscache
spec:
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: rediscache
status:
  loadBalancer: {}
