apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dbmeasures
  name: dbmeasures
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: dbmeasures
status:
  loadBalancer: {}
